"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CUSTOM_TEXT = exports.isTemplateKey = exports.INJECT_PROMPTS_PREFIX = exports.RIGHT_REPLACEMENT = exports.LEFT_REPLACEMENT = exports.MAIN_BRANCH = exports.TEMP_DIR = exports.TEMPLATE_CONFIG_FILE_NAME = exports.GIT_CACHE_BASE_URL = void 0;
const path_1 = require("path");
exports.GIT_CACHE_BASE_URL = path_1.resolve(__dirname, '../../.gitCache');
exports.TEMPLATE_CONFIG_FILE_NAME = '.ktconfig.json';
exports.TEMP_DIR = 'temp';
exports.MAIN_BRANCH = 'master';
exports.LEFT_REPLACEMENT = '【「『';
exports.RIGHT_REPLACEMENT = '』」】';
exports.INJECT_PROMPTS_PREFIX = '__';
exports.isTemplateKey = `${exports.INJECT_PROMPTS_PREFIX}isTemplate`;
exports.CUSTOM_TEXT = '自定义';
